sapling/tags/urls.py
from django.conf.urls.defaults import *
from tags.views import TagListView, TaggedList

urlpatterns = patterns('',
    url(r'^$', TagListView.as_view(), name='list'),
    url(r'^(?P<slug>.+)/*$', TaggedList.as_view(), name='tagged'),
)

sapling/urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.views.generic.simple import redirect_to
from django.contrib.admin.views.decorators import staff_member_required

import pages
import maps
import redirects
import dashboard
from users.admin import SubscribedList

admin.autodiscover()

urlpatterns = patterns('',
    (r'^map/', include(maps.site.urls)),
    (r'^tags$', redirect_to, {'url': '/tags/'}),
    (r'^tags/', include('sapling.tags.urls', 'tags', 'tags')),
    (r'^_redirect/', include(redirects.site.urls)),
    (r'^(?i)Users/', include('sapling.users.urls')),
    (r'^search/', include('sapling.search.urls')),
    (r'^', include('sapling.recentchanges.urls')),
    (r'^tools/', include(dashboard.site.urls)),

    # JS i18n support.
    (r'^jsi18n/(?P<packages>\S+?)/$', 'django.views.i18n.javascript_catalog'),

    (r'^admin$', redirect_to, {'url': '/admin/'}),
    (r'^admin/subscribers/$', staff_member_required(SubscribedList.as_view())),
    (r'^admin/', include(admin.site.urls)),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# This should only happen if you're using the local dev server with
# DEBUG=False.
if not settings.DEBUG:
    urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.STATIC_ROOT}),
        (r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),
    )

# Fall back to pages.
urlpatterns += patterns('',
    (r'^', include(pages.site.urls)),
)

sapling/tags/models.py
import re

from django.db import models
from django.db.utils import IntegrityError
from django.template.defaultfilters import stringfilter

from pages.models import Page
from versionutils import versioning, diff
from django.utils.html import strip_tags
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _


class Tag(models.Model):
    name = models.CharField(max_length=100)
    slug = models.CharField(editable=False, unique=True, max_length=100)

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.name = strip_tags(self.name)
        self.slug = slugify(self.name)
        if not self.slug:
            raise IntegrityError('Invalid tag name: %s' % self.name)
        super(Tag, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('tags:tagged', args=[self.slug])

    class Meta:
        ordering = ('slug',)
        verbose_name = _(u'Tag')
        verbose_name_plural = _(u'Tags')

versioning.register(Tag)


def slugify(value):
    # normalize unicode
    import unicodedata
    value = unicodedata.normalize('NFKD', unicode(value))
    # remove non-word characters
    misc_characters = re.compile(('[^\w]'), re.UNICODE)
    value = re.sub(misc_characters, '', value)
    return value.lower()
slugify = stringfilter(slugify)


class PageTagSet(models.Model):
    page = models.OneToOneField(Page)
    tags = models.ManyToManyField(Tag)

    def __unicode__(self):
        return ', '.join(map(unicode, self.tags.all()))

    class Meta:
        ordering = ('page__slug',)


class TagsFieldDiff(diff.BaseFieldDiff):
    template = 'tags/tags_diff.html'

    def get_diff(self):
        set1 = set(self.field1 and self.field1.all() or [])
        set2 = set(self.field2 and self.field2.all() or [])
        deleted = set1.difference(set2)
        added = set2.difference(set1)
        equal = set1.intersection(set2)
        return {'equal': equal, 'deleted': deleted, 'added': added}


class PageTagSetDiff(diff.BaseModelDiff):
    fields = (('tags', TagsFieldDiff),
              )


diff.register(PageTagSet, PageTagSetDiff)
versioning.register(PageTagSet)


import feeds  # To fire register() calls.
import signals  # To fire signals

sapling/tags/forms.py
from django import forms

from versionutils.merging.forms import MergeMixin
from tags.models import Tag, PageTagSet, slugify, TagsFieldDiff
from django.core.exceptions import ValidationError
from django.db.utils import IntegrityError
from django.utils.translation import ugettext as _, ungettext
from tags.widgets import TagEdit
from versionutils.versioning.forms import CommentMixin


def parse_tags(tagstring):
    words = [s.strip() for s in tagstring.split(',')]
    words = filter(lambda x: len(x) > 0, words)
    return list(set(words))


def tags_to_edit_string(tags):
    return ", ".join(tags)


class TagSetField(forms.ModelMultipleChoiceField):
    widget = TagEdit()

    def __init__(self, queryset, *args, **kwargs):
        super(TagSetField, self).__init__(queryset, *args, **kwargs)

    def clean(self, value):
        if not value:
            if self.required:
                raise ValidationError(self.error_messages['required'])
            else:
                return []
        self.run_validators(value)
        keys = []
        for word in parse_tags(value):
            try:
                tag, created = Tag.objects.get_or_create(slug=slugify(word),
                                                     defaults={'name': word})
                keys.append(tag.pk)
            except IntegrityError as e:
                raise ValidationError(e)
        return Tag.objects.filter(pk__in=keys)

    def prepare_value(self, value):
        if not hasattr(value, '__iter__'):
            return value
        tags = [t.name for t in self.queryset.filter(**{'pk__in': value})]
        return tags_to_edit_string(tags)


class PageTagSetForm(MergeMixin, CommentMixin, forms.ModelForm):
    class Meta:
        model = PageTagSet
        fields = ('tags',)
        exclude = ('comment',)  # we generate comment automatically

    tags = TagSetField(queryset=Tag.objects.all(), required=False)

    def pluralize_tag(self, list):
        if len(list) > 1:
            return Tag._meta.verbose_name_plural.lower()
        return Tag._meta.verbose_name.lower()

    def get_save_comment(self):
        comments = []
        short_comments = []
        previous = self.instance.pk and self.instance.tags or None
        d = TagsFieldDiff(previous, self.cleaned_data['tags'])
        diff = d.get_diff()
        deleted = ['"%s"' % t.name for t in diff['deleted']]
        added = ['"%s"' % t.name for t in diff['added']]
        if deleted:
            tag_name_pluralized = self.pluralize_tag(deleted)
            comments.append(ungettext(
                        'removed %(name)s %(deleted)s.',
                        'removed %(name)s %(deleted)s.',
                        len(deleted)
                ) % {
                    'deleted': ', '.join(deleted),
                    'name': tag_name_pluralized
                }
            )
            short_comments.append(ungettext(
                        'removed %(count)i %(name)s.',
                        'removed %(count)i %(name)s.',
                        len(deleted)
                ) % {
                    'count': len(deleted),
                    'name': tag_name_pluralized
                }
            )
        if added:
            tag_name_pluralized = self.pluralize_tag(added)
            comments.append(ungettext(
                        'added %(name)s %(added)s.',
                        'added %(name)s %(added)s.',
                        len(added)
                ) % {
                    'added': ', '.join(added),
                    'name': tag_name_pluralized
                }
            )
            short_comments.append(ungettext(
                        'added %(count)i %(name)s.',
                        'added %(count)i %(name)s.',
                        len(added)
                ) % {
                    'count': len(added),
                    'name': tag_name_pluralized
                }
            )
        if not comments:
            return _('no changes made')
        comments = _(' and ').join(comments)
        # with lots of tags, this can get too long for db field
        if len(comments) > 140:
            return _(' and ').join(short_comments)
        return comments

    def merge(self, yours, theirs, ancestor):
        your_set = set([t.pk for t in yours['tags']])
        their_set = set(theirs['tags'])
        if ancestor:
            # merge based on original id, so get that for each historic tag
            old_pks = [t.id for t in Tag.versions.filter(
                                            history_id__in=ancestor['tags'])]
            old_set = set(old_pks)
        else:
            old_set = set()
        common = your_set.intersection(their_set)
        merged = your_set.union(their_set).difference(old_set).union(common)
        yours['tags'] = Tag.objects.filter(pk__in=merged)
        return yours

sapling/tags/views.py
import copy
from dateutil.parser import parse as dateparser

from django.core.urlresolvers import reverse
from django.views.generic.list import ListView
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic.detail import DetailView
from django.conf import settings
from django.shortcuts import get_object_or_404
from django.db.models.aggregates import Count

from versionutils.versioning.views import VersionsList, RevertView, UpdateView
from versionutils.diff.views import CompareView
from utils.views import CreateObjectMixin, PermissionRequiredMixin,\
    Custom404Mixin
from tags.models import PageTagSet, Tag, slugify
from tags.forms import PageTagSetForm
from pages.models import Page
from maps.views import MapForTag
from maps.widgets import InfoMap


class PageNotFoundMixin(Custom404Mixin):
    def handler404(self, request, *args, **kwargs):
        return HttpResponseRedirect(reverse('pages:show',
                                            kwargs={'slug': kwargs['slug']}))


class TagListView(ListView):
    model = Tag

    def get_queryset(self):
        return super(TagListView, self).get_queryset().annotate(
                    num_pages=Count('pagetagset')).filter(num_pages__gt=0)


class TaggedList(ListView):
    model = PageTagSet

    def get_queryset(self):
        self.tag_name = slugify(self.kwargs['slug'])
        try:
            self.tag = Tag.objects.get(slug=self.tag_name)
            self.tag_name = self.tag.name
            return PageTagSet.objects.filter(tags=self.tag)
        except Tag.DoesNotExist:
            self.tag = None
            return PageTagSet.objects.none()

    def get_map_objects(self):
        if not self.tag:
            return None
        # We re-use the MapForTag view's logic here to embed a mini-map on the
        # tags list page
        map_view = MapForTag()
        map_view.kwargs = dict(tag=self.tag.slug)
        map_view.object_list = map_view.get_queryset()
        return map_view.get_map_objects()

    def get_context_data(self, *args, **kwargs):
        context = super(TaggedList, self).get_context_data(*args, **kwargs)
        context['tag'] = self.tag
        context['tag_name'] = self.tag_name
        map_objects = self.get_map_objects()
        if map_objects:
            # Remove the PanZoomBar on normal page views.
            olwidget_options = copy.deepcopy(getattr(settings,
                'OLWIDGET_DEFAULT_OPTIONS', {}))
            map_opts = olwidget_options.get('map_options', {})
            map_controls = map_opts.get('controls', [])
            if 'PanZoomBar' in map_controls:
                map_controls.remove('PanZoomBar')
            olwidget_options['map_options'] = map_opts
            olwidget_options['map_div_class'] = 'mapwidget small'
            context['map'] = InfoMap(
                map_objects,
                options=olwidget_options)
        return context


class PageTagSetUpdateView(PageNotFoundMixin, CreateObjectMixin, UpdateView):
    model = PageTagSet
    form_class = PageTagSetForm

    def get_object(self):
        page_slug = self.kwargs.get('slug')
        page = get_object_or_404(Page, slug=page_slug)
        try:
            return PageTagSet.objects.get(page=page)
        except PageTagSet.DoesNotExist:
            return PageTagSet(page=page)

    def get_success_url(self):
        next = self.request.POST.get('next', None)
        if next:
            return next
        return reverse('pages:tags', args=[self.kwargs.get('slug')])


class PageTagSetVersions(PageNotFoundMixin, VersionsList):
    def get_queryset(self):
        page_slug = self.kwargs.get('slug')
        try:
            self.page = get_object_or_404(Page, slug=page_slug)
            return self.page.pagetagset.versions.all()
        except PageTagSet.DoesNotExist:
            return PageTagSet.versions.none()

    def get_context_data(self, **kwargs):
        context = super(PageTagSetVersions, self).get_context_data(**kwargs)
        context['page'] = self.page
        return context


class PageTagSetVersionDetailView(DetailView):
    context_object_name = 'pagetagset'
    template_name = 'tags/pagetagset_version_detail.html'

    def get_object(self):
        page_slug = self.kwargs.get('slug')
        try:
            page = Page.objects.get(slug=page_slug)
            tags = page.pagetagset
            version = self.kwargs.get('version')
            date = self.kwargs.get('date')
            if version:
                return tags.versions.as_of(version=int(version))
            if date:
                return tags.versions.as_of(date=dateparser(date))
        except (Page.DoesNotExist, PageTagSet.DoesNotExist):
            return None

    def get_context_data(self, **kwargs):
        context = super(PageTagSetVersionDetailView,
                        self).get_context_data(**kwargs)
        context['date'] = self.object.version_info.date
        context['show_revision'] = True
        return context


class PageTagSetCompareView(CompareView):
    model = PageTagSet

    def get_object(self):
        page_slug = self.kwargs.get('slug')
        page = Page.objects.get(slug=page_slug)
        return page.pagetagset

    def get_context_data(self, **kwargs):
        context = super(PageTagSetCompareView, self).get_context_data(**kwargs)
        context['slug'] = self.kwargs['original_slug']
        return context


class PageTagSetRevertView(PermissionRequiredMixin, RevertView):
    model = PageTagSet
    context_object_name = 'pagetagset'
    permission = 'pages.change_page'

    def get_object(self):
        page_slug = self.kwargs.get('slug')
        page = Page.objects.get(slug=page_slug)
        return page.pagetagset.versions.as_of(version=int(
                                                    self.kwargs['version']))

    def get_protected_object(self):
        return self.object.page

    def get_success_url(self):
        # Redirect back to the file info page.
        return reverse('pages:tags-history', args=[self.kwargs['slug']])


def suggest_tags(request):
    """
    Simple tag suggest.
    """
    # XXX TODO: Break this out when doing the API work.
    import json

    term = request.GET.get('term', None)
    if not term:
        return HttpResponse('')
    results = Tag.objects.filter(name__istartswith=term).exclude(
                                                            pagetagset=None)
    results = [t.name for t in results]
    return HttpResponse(json.dumps(results))

sapling/tags/templates/tags/base.html
{% extends "site/base.html" %}

{% block body %}
<body>
   <div class="tagpage">
   {% block everything_wrapper %}
        {{ block.super }}
   {% endblock %}
   </div>
</body>
{% endblock %}

sapling/tags/templates/tags/pagetagset_confirm_revert.html
{% extends "tags/pagetagset_version_detail.html" %}
{% load i18n %}

{% block search_robots %}
<meta name="robots" content="noindex,nofollow">
{% endblock %}

{% block dialog %}
<div id="dialog">
 <form method="post" action="">{% csrf_token %}
    <ul>
      {{ form.as_ul }}
    </ul>
    <input type="submit" value="{% trans 'Revert' %}"/>
 </form>
</div>
{% endblock %}

{% block extras %}
{% endblock %}

sapling/tags/templates/tags/pagetagset_diff.html
{% extends "tags/base.html" %}
{% load i18n %}
{% load diff_tags %}
{% load tags_tags %}

{% block search_robots %}
<meta name="robots" content="noindex,nofollow">
{% endblock %}

{% block media %}
  {{ block.super }}
  <style>
    del {
      background: #FDC6C6;
      text-decoration: none;
    }
    ins {
      background: #b4ff78;
      text-decoration: none;
    }
    td.revision_details {
      font-style: italic;
    }
  </style>
  {% page_tags_form_media %}
{% endblock %}

{% block title %}{% blocktrans with new_name=new.page.name %}Differences for tag versions for {{ new_name }}{% endblocktrans %}{% endblock %}
{% block header_title %}{% blocktrans with new_name=new.page.name %}Differences for tag versions for {{ new_name }}{% endblocktrans %}{% endblock %}

{% block content %}
  <table width="100%">
    <thead>
        <tr>
            <td class="revision_details">
                {% if old %}
                  {% trans "Revision" %} {{ old.version_info.version_number }}
                  ({{ old.version_info.date }} {% trans "by" %} {{ old.version_info.user_link|safe }})
                {% endif %}
            </td>
            <td class="revision_details">
                {% trans "Revision" %} {{ new.version_info.version_number }}
                ({{ new.version_info.date }} {% trans "by" %} {{ new.version_info.user_link|safe }})
            </td>
        </tr>
        <tr>
            <td>
                <del>{% trans "Deletions are marked like this" %}</del>
            </td>
            <td>
                <ins>{% trans "Additions are marked like this" %}</ins>
            </td>
        </tr>
    </thead>
    {% diff old new as pagetagset_diff %}
    <tbody valign="top">
        {{ pagetagset_diff.tags }}
    </tbody>
  </table>
  <p>
      <a href="{% url pages:tags-history slug=pagetagset.page.slug %}">{% trans "Tags history" %}</a>
  </p>
{% endblock %}

sapling/tags/templates/tags/pagetagset_form.html
{% extends "tags/base.html" %}
{% load i18n %}

{% block search_robots %}
<meta name="robots" content="noindex,nofollow">
{% endblock %}

{% block media %}
  {{ block.super }}
  {{ form.media }}
{% endblock %}

{% block title %}{% trans "Tags for" %} {{ pagetagset.page.name }} - {{ block.super }}{% endblock %}
{% block header_title %}{% trans "Tags for" %} <a href="{% url pages:show slug=pagetagset.page.pretty_slug %}">{{ pagetagset.page.name }}</a>{% endblock %}

{% block content %}
    <div id="object_tags">
    {% include "tags/pagetagset_form_snippet.html" %}
    </div>
{% endblock %}

sapling/tags/templates/tags/pagetagset_form_snippet.html
{% load i18n %}

<form action="{% url pages:tags slug=form.instance.page.pretty_slug %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="hidden" name="next" value="{{ request.path }}"/>
    <br/>
    <input type="submit" name="save" class="little" value="{% trans "Save" %}"/>
</form>

sapling/tags/templates/tags/pagetagset_list.html
{% extends "tags/base.html" %}
{% load i18n %}

{% block title %}{% trans "Tags" %} / {{ tag_name }} - {{ block.super }}{% endblock %}
{% block header_title %}<a href="{% url tags:list %}">{% trans "Tags" %}</a> / {{ tag_name }}{% endblock %}

{% block media %}
  {{ block.super }}
  {% if map %}{{ map.media }}{% endif %}
{% endblock %}

{% block content %}
  {% include "tags/tagged_list_snippet.html" %}
{% endblock %}

sapling/tags/templates/tags/pagetagset_version_detail.html
{% extends "tags/base.html" %}
{% load i18n %}
{% load tags_tags %}

{% block media %}
  {{ block.super }}
  {{ form.media }}
  {% page_tags_form_media %}
{% endblock %}

{% block title %}{% trans "Tags for " %} {{ pagetagset.page.name }} - {{ block.super }}{% endblock %}
{% block header_title %}{% trans "Tags for" %} <a href="{% url pages:show slug=pagetagset.page.pretty_slug %}">{{ pagetagset.page.name }}</a>{% endblock %}

{% block content %}
    {% if show_revision %}
      <em class="revision_details">
          {% trans "Revision" %} {{ pagetagset.version_info.version_number }}
          ({{ pagetagset.version_info.date }} {% trans "by" %} {{ pagetagset.version_info.user_link|safe }})
      </em>
    {% endif %}
    <div id="object_tags">
    {% with pagetagset.tags.all as tag_list %}
      {% include "tags/tag_list_snippet.html" %}
    {% endwith %}
    </div>
{% endblock %}

sapling/tags/templates/tags/pagetagset_versions.html
{% extends "tags/base.html" %}
{% load i18n %}
{% load tags_tags %}

{% block media %}
  {{ block.super }}
  {% page_tags_form_media %}
{% endblock %}

{% block title %}{% trans "Tags for " %} {{ page.name }} - {{ block.super }}{% endblock %}
{% block header_title %}{% trans "Tags for" %} <a href="{% url pages:show slug=page.slug %}">{{ page.name }}</a>{% endblock %}

{% block content %}
  <div id="object_tags">
  {% if page.pagetagset.tags.exists %}
    {% page_tags page %}
  {% else %}
    {% url pages:tags slug=page.slug as page_url %}
    {% blocktrans %}
        This page has no tags.  <a href="{{ page_url }}">Add some!</a>
    {% endblocktrans %}
  {% endif %}
  </div>
  <br/>
  <h3>{% trans "Previous versions:" %}</h3>
  {% include "utils/history/form.html" %}
{% endblock %}

sapling/tags/templates/tags/tag_list.html
{% extends "tags/base.html" %}
{% load i18n %}

{% block title %}{% trans "Tags" %} - {{ block.super }}{% endblock %}
{% block header_title %}{% trans "All tags" %}{% endblock %}

{% block media %}
  {{ block.super }}
  <script type="text/javascript" src="{{ STATIC_URL }}js/jquery/jquery-1.7.min.js"></script>
  <script type="text/javascript" src="{{ STATIC_URL }}js/jquery/jquery-ui-1.8.16.custom.min.js"></script>
{% endblock %}

{% block content %}
  {% if tag_list %}
    <div id="tabs">
        <ul style="display: none;">
        <li><a href="#tags_by_name">{% trans "Alphabetical" %}</a></li>
        <li><a href="#tags_by_num_pages">{% trans "Most popular" %}</a></li>
        <li><a href="#tags_cloud">{% trans "As a cloud" %}</a></li>
        </ul>
        <div id="tags_by_name">
        {% include "tags/tag_list_snippet.html" %}
        </div>
        <div id="tags_by_num_pages">
        {% include "tags/tag_list_by_num_pages.html" %}
        </div>
        <div id="tags_cloud">
        {% include "tags/tag_cloud.html" %}
        </div>
    </div>
    <style>
        .ui-tabs-nav {
            list-style: none;
            margin: 0 0 1.5em 0;
        }
        .ui-tabs-nav li {
            margin: 0;
            margin-right: 4em;
            display: inline;
        }
        .ui-tabs-selected a:link, .ui-tabs-selected a:hover,
        .ui-tabs-selected a:visited {
            cursor: default;
            text-decoration: none;
            color: #444;
        }
        .ui-tabs-hide {
            display: none;
        }
    </style>
    <script type="text/javascript">
        $(function() {
            $( "#tabs > ul" ).show();
            $( "#tabs" ).tabs();
        });
    </script>
  {% else %}
    {% trans "There are no tags. Add some!" %}
  {% endif %}
{% endblock %}

sapling/tags/templates/tags/tag_list_by_num_pages.html
<style>
    .num_pages {
        color: #AAA;
        font-size: 80%;
    }
</style>
<ul class="tag-list">
{% for tag in tag_list|dictsortreversed:"num_pages" %}
  <li class="tag"><a href="{% url tags:tagged slug=tag.slug %}">{{ tag.name }}</a> <span class="num_pages">x {{ tag.num_pages}}</span>
  </li>
{% endfor %}
</ul>

sapling/tags/templates/tags/tag_list_snippet.html
{% if tag_list %}
  <ul class="tag-list">
  {% for tag in tag_list %}
    <li class="tag"><a href="{% url tags:tagged slug=tag.slug %}" rel="tag">{{ tag.name }}</a></li>
  {% endfor %}
  </ul>
{% endif %}

sapling/tags/templates/tags/tagedit.html
<script>
    $(function(){
       $('input#{{ id }}').tagedit({
           autocompleteURL: '{{ autocomplete_url }}'
       }) 
    });
</script>

sapling/tags/templates/tags/tagged_list_snippet.html
{% load i18n %}

{% if map %}
  {{ map.media }}
  <div id="map">
    {{ map }}
    <div class="info"><a href="{% url maps:tagged tag=tag.slug %}">{% trans "View map" %}</a></div>
  </div>
{% endif %}
{% if pagetagset_list %}
  <ul>
  {% for pagetags in pagetagset_list %}
    <li><a href="{% url pages:show slug=pagetags.page.pretty_slug %}">{{ pagetags.page.name }}</a></li>
  {% endfor %}
  </ul>
{% else %}
  {% blocktrans %}There are no pages with the tag "{{ tag_name }}".{% endblocktrans %}
{% endif %}

sapling/tags/templates/tags/tags_diff.html
{% spaceless %}
  <tr>
  <td><div id="object_tags">
    <ul class="tag-list">
    {% for tag in equal %}
      <li class="tag"><a href="{% url tags:tagged slug=tag.slug %}">{{ tag.name }}</a></li>
    {% endfor %}
    {% for tag in deleted %}
      <li class="tag del"><a href="{% url tags:tagged slug=tag.slug %}">{{ tag.name }}</a></li>
    {% endfor %}
    </ul>
    </div>
  </td>
  <td><div id="object_tags">
    <ul class="tag-list">
    {% for tag in equal %}
      <li class="tag"><a href="{% url tags:tagged slug=tag.slug %}">{{ tag.name }}</a></li>
    {% endfor %}
    {% for tag in added %}
      <li class="tag ins"><a href="{% url tags:tagged slug=tag.slug %}">{{ tag.name }}</li>
    {% endfor %}
    </ul>
    </div>
  </td>
  </tr>
{% endspaceless %}